// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5b6xkhFlaUAsUAHqXyWhAeIWimGmOtkA',
    appId: '1:363870034801:web:37340733438b50c870f4d0',
    messagingSenderId: '363870034801',
    projectId: 'bloodpoint-9dd33',
    authDomain: 'bloodpoint-9dd33.firebaseapp.com',
    storageBucket: 'bloodpoint-9dd33.appspot.com',
    measurementId: 'G-EEFT00BS1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo-urwWr_xHNKNM-xndNdxUoyxEz9xhpg',
    appId: '1:363870034801:android:5e6182b25afa1eb370f4d0',
    messagingSenderId: '363870034801',
    projectId: 'bloodpoint-9dd33',
    storageBucket: 'bloodpoint-9dd33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0bHvutwKzuCJkCFGbq1MaNBjtq0tW_2M',
    appId: '1:363870034801:ios:f011bf0b36dbb7cf70f4d0',
    messagingSenderId: '363870034801',
    projectId: 'bloodpoint-9dd33',
    storageBucket: 'bloodpoint-9dd33.appspot.com',
    iosBundleId: 'com.example.bloodDonor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0bHvutwKzuCJkCFGbq1MaNBjtq0tW_2M',
    appId: '1:363870034801:ios:02a3ce1fe73f7fc970f4d0',
    messagingSenderId: '363870034801',
    projectId: 'bloodpoint-9dd33',
    storageBucket: 'bloodpoint-9dd33.appspot.com',
    iosBundleId: 'com.example.bloodDonor.RunnerTests',
  );
}
